FROM golang:1.9-alpine

RUN apk --update add curl git nodejs nodejs-npm bash build-base perl fontconfig openssh tar gzip ca-certificates
RUN npm install -g yarn@latest
RUN mkdir -p /usr/share && \
  cd /usr/share \
  && curl -L https://github.com/Overbryd/docker-phantomjs-alpine/releases/download/2.11/phantomjs-alpine-x86_64.tar.bz2 | tar xj \
  && ln -s /usr/share/phantomjs/phantomjs /usr/bin/phantomjs \
  && phantomjs --version

WORKDIR /go/src/github.com/checkr/flagr
ADD . .
RUN make deps
