swagger: "2.0"
info:
  description: "This is a sample server."
  version: "1.0.0"
  title: "Swagger Sample API"
host: "api.example.com"
basePath: "/v1"
schemes:
  - "https"
paths:
  /flags/{flagID}:
    get:
      tags:
        - flag
      operationId: getFlag
      parameters:
        - in: path
          name: flagID
          description: numeric ID of the flag to get
          required: true
          type: integer
          format: int64
          minimum: 1
      responses:
        200:
          description: returns the flag
          schema:
            $ref: "#/definitions/flag"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - flag
      operationId: deleteFlag
      parameters:
        - in: path
          name: flagID
          description: numeric ID of the flag
          required: true
          type: integer
          format: int64
          minimum: 1
      responses:
        200:
          description: OK deleted
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    put:
      tags:
        - flag
      operationId: putFlag
      parameters:
        - in: path
          name: flagID
          description: numeric ID of the flag to get
          required: true
          type: integer
          format: int64
          minimum: 1
        - in: body
          name: body
          description: update a flag
          required: true
          schema:
            $ref: "#/definitions/putFlagRequest"
      responses:
        200:
          description: returns the flag
          schema:
            $ref: "#/definitions/flag"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
  /latches:
    post:
      tags:
        - latch
      operationId: createLatch
      parameters:
        - in: body
          name: body
          description: Latch object that needs to be added
          required: true
          schema:
            $ref: "#/definitions/flag"
      responses:
        200:
          description: Latch created successfully
          schema:
            $ref: "#/definitions/flag"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
definitions:
  flag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  error:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
  putFlagRequest:
    type: object
    properties:
      name:
        type: string