// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewDeleteGlobalWebhookParams creates a new DeleteGlobalWebhookParams object
//
// There are no default values defined in the spec.
func NewDeleteGlobalWebhookParams() DeleteGlobalWebhookParams {

	return DeleteGlobalWebhookParams{}
}

// DeleteGlobalWebhookParams contains all the bound params for the delete global webhook operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteGlobalWebhook
type DeleteGlobalWebhookParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*numeric ID of the webhook
	  Required: true
	  Minimum: 1
	  In: path
	*/
	WebhookID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteGlobalWebhookParams() beforehand.
func (o *DeleteGlobalWebhookParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rWebhookID, rhkWebhookID, _ := route.Params.GetOK("webhookID")
	if err := o.bindWebhookID(rWebhookID, rhkWebhookID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindWebhookID binds and validates parameter WebhookID from path.
func (o *DeleteGlobalWebhookParams) bindWebhookID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("webhookID", "path", "int64", raw)
	}
	o.WebhookID = value

	if err := o.validateWebhookID(formats); err != nil {
		return err
	}

	return nil
}

// validateWebhookID carries on validations for parameter WebhookID
func (o *DeleteGlobalWebhookParams) validateWebhookID(formats strfmt.Registry) error {

	if err := validate.MinimumInt("webhookID", "path", o.WebhookID, 1, false); err != nil {
		return err
	}

	return nil
}
