// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// FindGlobalWebhooksOKCode is the HTTP code returned for type FindGlobalWebhooksOK
const FindGlobalWebhooksOKCode int = 200

/*
FindGlobalWebhooksOK all webhooks

swagger:response findGlobalWebhooksOK
*/
type FindGlobalWebhooksOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Webhook `json:"body,omitempty"`
}

// NewFindGlobalWebhooksOK creates FindGlobalWebhooksOK with default headers values
func NewFindGlobalWebhooksOK() *FindGlobalWebhooksOK {

	return &FindGlobalWebhooksOK{}
}

// WithPayload adds the payload to the find global webhooks o k response
func (o *FindGlobalWebhooksOK) WithPayload(payload []*models.Webhook) *FindGlobalWebhooksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find global webhooks o k response
func (o *FindGlobalWebhooksOK) SetPayload(payload []*models.Webhook) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindGlobalWebhooksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Webhook, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
FindGlobalWebhooksDefault generic error response

swagger:response findGlobalWebhooksDefault
*/
type FindGlobalWebhooksDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindGlobalWebhooksDefault creates FindGlobalWebhooksDefault with default headers values
func NewFindGlobalWebhooksDefault(code int) *FindGlobalWebhooksDefault {
	if code <= 0 {
		code = 500
	}

	return &FindGlobalWebhooksDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find global webhooks default response
func (o *FindGlobalWebhooksDefault) WithStatusCode(code int) *FindGlobalWebhooksDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find global webhooks default response
func (o *FindGlobalWebhooksDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the find global webhooks default response
func (o *FindGlobalWebhooksDefault) WithPayload(payload *models.Error) *FindGlobalWebhooksDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find global webhooks default response
func (o *FindGlobalWebhooksDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindGlobalWebhooksDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
