// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutGlobalWebhookHandlerFunc turns a function with the right signature into a put global webhook handler
type PutGlobalWebhookHandlerFunc func(PutGlobalWebhookParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutGlobalWebhookHandlerFunc) Handle(params PutGlobalWebhookParams) middleware.Responder {
	return fn(params)
}

// PutGlobalWebhookHandler interface for that can handle valid put global webhook params
type PutGlobalWebhookHandler interface {
	Handle(PutGlobalWebhookParams) middleware.Responder
}

// NewPutGlobalWebhook creates a new http.Handler for the put global webhook operation
func NewPutGlobalWebhook(ctx *middleware.Context, handler PutGlobalWebhookHandler) *PutGlobalWebhook {
	return &PutGlobalWebhook{Context: ctx, Handler: handler}
}

/*
	PutGlobalWebhook swagger:route PUT /webhooks/{webhookID} webhook putGlobalWebhook

PutGlobalWebhook put global webhook API
*/
type PutGlobalWebhook struct {
	Context *middleware.Context
	Handler PutGlobalWebhookHandler
}

func (o *PutGlobalWebhook) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutGlobalWebhookParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
