// Code generated by go-swagger; DO NOT EDIT.

package variant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/checkr/flagr/swagger_gen/models"
)

// PutVariantOKCode is the HTTP code returned for type PutVariantOK
const PutVariantOKCode int = 200

/*PutVariantOK variant just updated

swagger:response putVariantOK
*/
type PutVariantOK struct {

	/*
	  In: Body
	*/
	Payload *models.Variant `json:"body,omitempty"`
}

// NewPutVariantOK creates PutVariantOK with default headers values
func NewPutVariantOK() *PutVariantOK {

	return &PutVariantOK{}
}

// WithPayload adds the payload to the put variant o k response
func (o *PutVariantOK) WithPayload(payload *models.Variant) *PutVariantOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put variant o k response
func (o *PutVariantOK) SetPayload(payload *models.Variant) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutVariantOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutVariantDefault generic error response

swagger:response putVariantDefault
*/
type PutVariantDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutVariantDefault creates PutVariantDefault with default headers values
func NewPutVariantDefault(code int) *PutVariantDefault {
	if code <= 0 {
		code = 500
	}

	return &PutVariantDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put variant default response
func (o *PutVariantDefault) WithStatusCode(code int) *PutVariantDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put variant default response
func (o *PutVariantDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put variant default response
func (o *PutVariantDefault) WithPayload(payload *models.Error) *PutVariantDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put variant default response
func (o *PutVariantDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutVariantDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
