// Code generated by go-swagger; DO NOT EDIT.

package distribution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindDistributionsHandlerFunc turns a function with the right signature into a find distributions handler
type FindDistributionsHandlerFunc func(FindDistributionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindDistributionsHandlerFunc) Handle(params FindDistributionsParams) middleware.Responder {
	return fn(params)
}

// FindDistributionsHandler interface for that can handle valid find distributions params
type FindDistributionsHandler interface {
	Handle(FindDistributionsParams) middleware.Responder
}

// NewFindDistributions creates a new http.Handler for the find distributions operation
func NewFindDistributions(ctx *middleware.Context, handler FindDistributionsHandler) *FindDistributions {
	return &FindDistributions{Context: ctx, Handler: handler}
}

/* FindDistributions swagger:route GET /flags/{flagID}/segments/{segmentID}/distributions distribution findDistributions

FindDistributions find distributions API

*/
type FindDistributions struct {
	Context *middleware.Context
	Handler FindDistributionsHandler
}

func (o *FindDistributions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindDistributionsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
