// Code generated by go-swagger; DO NOT EDIT.

package latch

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateLatchHandlerFunc turns a function with the right signature into a create latch handler
type CreateLatchHandlerFunc func(CreateLatchParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateLatchHandlerFunc) Handle(params CreateLatchParams) middleware.Responder {
	return fn(params)
}

// CreateLatchHandler interface for that can handle valid create latch params
type CreateLatchHandler interface {
	Handle(CreateLatchParams) middleware.Responder
}

// NewCreateLatch creates a new http.Handler for the create latch operation
func NewCreateLatch(ctx *middleware.Context, handler CreateLatchHandler) *CreateLatch {
	return &CreateLatch{Context: ctx, Handler: handler}
}

/*
	CreateLatch swagger:route POST /latches latch createLatch

CreateLatch create latch API
*/
type CreateLatch struct {
	Context *middleware.Context
	Handler CreateLatchHandler
}

func (o *CreateLatch) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateLatchParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
