FROM golang:1.25.6-alpine as go_builder
WORKDIR /go/src/github.com/openflagr/flagr
RUN apk add --no-cache git make build-base
ADD . .
ENV CGO_ENABLED=0
ENV GOEXPERIMENT=greenteagc
RUN make build

FROM alpine

COPY --from=go_builder /go/src/github.com/openflagr/flagr/flagr .

ENV HOST=0.0.0.0
ENV PORT=18000
ENV FLAGR_DB_DBDRIVER=sqlite3
ENV FLAGR_RECORDER_ENABLED=false
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser
EXPOSE 18000

CMD "./flagr"