######################################
# Prepare go_builder
######################################
FROM golang:1.17 as go_builder
WORKDIR /go/src/github.com/openflagr/flagr
ADD . .
RUN make build

######################################
# Copy from builder to alpine image
######################################
FROM frolvlad/alpine-glibc:alpine-3.15
RUN apk add --no-cache curl
WORKDIR /go/src/github.com/openflagr/flagr
COPY --from=go_builder /go/src/github.com/openflagr/flagr/flagr ./flagr
VOLUME ["/data"]
ENV HOST=0.0.0.0
ENV PORT=18000
ENV FLAGR_DB_DBDRIVER=sqlite3
ENV FLAGR_RECORDER_ENABLED=false
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser
EXPOSE 18000
CMD ./flagr
