version: "3.6"

networks:
  default:
    external:
      name: flagr_integration_tests

services:
  mysql:
    image: mysql:5.6
    container_name: flagr-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "flagr"

  mysql8:
    image: mysql:8
    container_name: flagr-mysql8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "flagr"

  postgres14:
    image: 063399264027.dkr.ecr.eu-west-1.amazonaws.com/tradeshift-base/tradeshift-postgres-alpine-14-alpine:latest
    container_name: flagr-postgres14
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "test"
      POSTGRES_DB: "flagr"

  postgres16:
    image: 063399264027.dkr.ecr.eu-west-1.amazonaws.com/tradeshift-base/tradeshift-postgres-alpine-16-alpine:latest
    container_name: flagr-postgres16
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "test"
      POSTGRES_DB: "flagr"

  checkr_flagr_with_sqlite:
    image: checkr/flagr:1.1.12
    environment:
      FLAGR_DB_DBDRIVER: "sqlite3"
      FLAGR_DB_DBCONNECTIONSTR: "/tmp/flagr.sqlite3"
    command: sh -c "sleep 15 && ./flagr"

  flagr_with_sqlite:
    image: flagr_integration_tests
    environment:
      FLAGR_DB_DBDRIVER: "sqlite3"
      FLAGR_DB_DBCONNECTIONSTR: "/tmp/flagr.sqlite3"
    command: sh -c "sleep 15 && ./flagr"

  flagr_with_mysql:
    image: flagr_integration_tests
    environment:
      FLAGR_DB_DBDRIVER: "mysql"
      FLAGR_DB_DBCONNECTIONSTR: "root:@tcp(mysql:3306)/flagr?parseTime=true"
    command: sh -c "sleep 15 && ./flagr"

  flagr_with_mysql8:
    image: flagr_integration_tests
    environment:
      FLAGR_DB_DBDRIVER: "mysql"
      FLAGR_DB_DBCONNECTIONSTR: "root:@tcp(mysql8:3306)/flagr?parseTime=true"
    command: sh -c "sleep 15 && ./flagr"

  flagr_with_postgres14:
    image: flagr_integration_tests
    environment:
      FLAGR_DB_DBDRIVER: "postgres"
      FLAGR_DB_DBCONNECTIONSTR: "sslmode=disable host=postgres9 user=test password=test dbname=flagr"
    command: sh -c "sleep 15 && ./flagr"

  flagr_with_postgres16:
    image: flagr_integration_tests
    environment:
      FLAGR_DB_DBDRIVER: "postgres"
      FLAGR_DB_DBCONNECTIONSTR: "sslmode=disable host=postgres13 user=test password=test dbname=flagr"
    command: sh -c "sleep 15 && ./flagr"

  shakedown:
    image: zhouzhuojie/docker-shakedown
    container_name: flagr-shakedown
    command: sh -c "tail -F /dev/null"
