// Code generated by go-swagger; DO NOT EDIT.

package flag

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DuplicateFlagHandlerFunc turns a function with the right signature into a duplicate flag handler
type DuplicateFlagHandlerFunc func(DuplicateFlagParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DuplicateFlagHandlerFunc) Handle(params DuplicateFlagParams) middleware.Responder {
	return fn(params)
}

// DuplicateFlagHandler interface for that can handle valid duplicate flag params
type DuplicateFlagHandler interface {
	Handle(DuplicateFlagParams) middleware.Responder
}

// NewDuplicateFlag creates a new http.Handler for the duplicate flag operation
func NewDuplicateFlag(ctx *middleware.Context, handler DuplicateFlagHandler) *DuplicateFlag {
	return &DuplicateFlag{Context: ctx, Handler: handler}
}

/*
	DuplicateFlag swagger:route POST /flags/{flagID}/duplicate flag duplicateFlag

DuplicateFlag duplicate flag API
*/
type DuplicateFlag struct {
	Context *middleware.Context
	Handler DuplicateFlagHandler
}

func (o *DuplicateFlag) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewDuplicateFlagParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
