// Code generated by go-swagger; DO NOT EDIT.

package flag

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFlagSnapshotMaxIDHandlerFunc turns a function with the right signature into a get flag snapshot max ID handler
type GetFlagSnapshotMaxIDHandlerFunc func(GetFlagSnapshotMaxIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFlagSnapshotMaxIDHandlerFunc) Handle(params GetFlagSnapshotMaxIDParams) middleware.Responder {
	return fn(params)
}

// GetFlagSnapshotMaxIDHandler interface for that can handle valid get flag snapshot max ID params
type GetFlagSnapshotMaxIDHandler interface {
	Handle(GetFlagSnapshotMaxIDParams) middleware.Responder
}

// NewGetFlagSnapshotMaxID creates a new http.Handler for the get flag snapshot max ID operation
func NewGetFlagSnapshotMaxID(ctx *middleware.Context, handler GetFlagSnapshotMaxIDHandler) *GetFlagSnapshotMaxID {
	return &GetFlagSnapshotMaxID{Context: ctx, Handler: handler}
}

/*
	GetFlagSnapshotMaxID swagger:route GET /flags/snapshots/max_id flag getFlagSnapshotMaxId

Get the max flag snapshot ID (config change version)

Returns the highest (most recent) flag_snapshot id. flag_snapshot is an append-only changelog — every flag configuration mutation (create, update, delete, restore of flags, segments, variants, constraints, distributions, or tags) inserts a new row with a monotonically increasing id. This makes the max id a lightweight single source of truth for detecting any configuration change.
Consumers can store this value and poll it periodically: if the value changes, at least one flag's configuration has been modified and caches should be invalidated. This is vastly more efficient than polling the flags list or individual flags.
*/
type GetFlagSnapshotMaxID struct {
	Context *middleware.Context
	Handler GetFlagSnapshotMaxIDHandler
}

func (o *GetFlagSnapshotMaxID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFlagSnapshotMaxIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
