// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// GetFlagSnapshotMaxIDOKCode is the HTTP code returned for type GetFlagSnapshotMaxIDOK
const GetFlagSnapshotMaxIDOKCode int = 200

/*
GetFlagSnapshotMaxIDOK returns the max flag_snapshot id

swagger:response getFlagSnapshotMaxIdOK
*/
type GetFlagSnapshotMaxIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.FlagSnapshotMaxID `json:"body,omitempty"`
}

// NewGetFlagSnapshotMaxIDOK creates GetFlagSnapshotMaxIDOK with default headers values
func NewGetFlagSnapshotMaxIDOK() *GetFlagSnapshotMaxIDOK {

	return &GetFlagSnapshotMaxIDOK{}
}

// WithPayload adds the payload to the get flag snapshot max Id o k response
func (o *GetFlagSnapshotMaxIDOK) WithPayload(payload *models.FlagSnapshotMaxID) *GetFlagSnapshotMaxIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get flag snapshot max Id o k response
func (o *GetFlagSnapshotMaxIDOK) SetPayload(payload *models.FlagSnapshotMaxID) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFlagSnapshotMaxIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetFlagSnapshotMaxIDDefault generic error response

swagger:response getFlagSnapshotMaxIdDefault
*/
type GetFlagSnapshotMaxIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetFlagSnapshotMaxIDDefault creates GetFlagSnapshotMaxIDDefault with default headers values
func NewGetFlagSnapshotMaxIDDefault(code int) *GetFlagSnapshotMaxIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetFlagSnapshotMaxIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get flag snapshot max ID default response
func (o *GetFlagSnapshotMaxIDDefault) WithStatusCode(code int) *GetFlagSnapshotMaxIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get flag snapshot max ID default response
func (o *GetFlagSnapshotMaxIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get flag snapshot max ID default response
func (o *GetFlagSnapshotMaxIDDefault) WithPayload(payload *models.Error) *GetFlagSnapshotMaxIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get flag snapshot max ID default response
func (o *GetFlagSnapshotMaxIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFlagSnapshotMaxIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
