// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutSegmentsReorderHandlerFunc turns a function with the right signature into a put segments reorder handler
type PutSegmentsReorderHandlerFunc func(PutSegmentsReorderParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutSegmentsReorderHandlerFunc) Handle(params PutSegmentsReorderParams) middleware.Responder {
	return fn(params)
}

// PutSegmentsReorderHandler interface for that can handle valid put segments reorder params
type PutSegmentsReorderHandler interface {
	Handle(PutSegmentsReorderParams) middleware.Responder
}

// NewPutSegmentsReorder creates a new http.Handler for the put segments reorder operation
func NewPutSegmentsReorder(ctx *middleware.Context, handler PutSegmentsReorderHandler) *PutSegmentsReorder {
	return &PutSegmentsReorder{Context: ctx, Handler: handler}
}

/* PutSegmentsReorder swagger:route PUT /flags/{flagID}/segments/reorder segment putSegmentsReorder

PutSegmentsReorder put segments reorder API

*/
type PutSegmentsReorder struct {
	Context *middleware.Context
	Handler PutSegmentsReorderHandler
}

func (o *PutSegmentsReorder) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutSegmentsReorderParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
