// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// CreateConstraintRequest create constraint request
//
// swagger:model createConstraintRequest
type CreateConstraintRequest struct {

	// jev
	Jev *JevQuestion `json:"jev,omitempty"`

	// operator
	// Required: true
	// Min Length: 1
	Operator *string `json:"operator"`

	// The property name from the entity context to evaluate. Supports nested field access: use dots (e.g., `user.name`) for nested objects and brackets (e.g., `users[0]`) for array indices.
	//
	// Required: true
	// Min Length: 1
	Property *string `json:"property"`

	// value
	// Required: true
	// Min Length: 1
	Value *string `json:"value"`
}

// Validate validates this create constraint request
func (m *CreateConstraintRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateJev(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOperator(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProperty(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateConstraintRequest) validateJev(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Jev) { // not required
		return nil
	}

	if m.Jev != nil {
		if err := m.Jev.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("jev")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("jev")
			}

			return err
		}
	}

	return nil
}

func (m *CreateConstraintRequest) validateOperator(formats strfmt.Registry) error {

	if err := validate.Required("operator", "body", m.Operator); err != nil {
		return err
	}

	if err := validate.MinLength("operator", "body", *m.Operator, 1); err != nil {
		return err
	}

	return nil
}

func (m *CreateConstraintRequest) validateProperty(formats strfmt.Registry) error {

	if err := validate.Required("property", "body", m.Property); err != nil {
		return err
	}

	if err := validate.MinLength("property", "body", *m.Property, 1); err != nil {
		return err
	}

	return nil
}

func (m *CreateConstraintRequest) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	if err := validate.MinLength("value", "body", *m.Value, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this create constraint request based on the context it is used
func (m *CreateConstraintRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateJev(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateConstraintRequest) contextValidateJev(ctx context.Context, formats strfmt.Registry) error {

	if m.Jev != nil {

		if typeutils.IsZero(m.Jev) { // not required
			return nil
		}

		if err := m.Jev.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("jev")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("jev")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateConstraintRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateConstraintRequest) UnmarshalBinary(b []byte) error {
	var res CreateConstraintRequest
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
