// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// CreateEnricherRequest create enricher request
//
// swagger:model createEnricherRequest
type CreateEnricherRequest struct {

	// namespace-specific configuration; the jev namespace expects an object with a questions map
	// Required: true
	Config any `json:"config"`

	// namespace
	// Required: true
	// Min Length: 1
	Namespace *string `json:"namespace"`
}

// Validate validates this create enricher request
func (m *CreateEnricherRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNamespace(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateEnricherRequest) validateConfig(formats strfmt.Registry) error {

	if m.Config == nil {
		return errors.Required("config", "body", nil)
	}

	return nil
}

func (m *CreateEnricherRequest) validateNamespace(formats strfmt.Registry) error {

	if err := validate.Required("namespace", "body", m.Namespace); err != nil {
		return err
	}

	if err := validate.MinLength("namespace", "body", *m.Namespace, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create enricher request based on context it is used
func (m *CreateEnricherRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateEnricherRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateEnricherRequest) UnmarshalBinary(b []byte) error {
	var res CreateEnricherRequest
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
