// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// DatarSummaryFlag datar summary flag
//
// swagger:model datarSummaryFlag
type DatarSummaryFlag struct {

	// description
	Description string `json:"description,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// flag ID
	FlagID int64 `json:"flagID,omitempty"`

	// flag key
	FlagKey string `json:"flagKey,omitempty"`

	// last evaluated at
	// Format: date-time
	LastEvaluatedAt strfmt.DateTime `json:"lastEvaluatedAt,omitempty"`

	// total eval count
	TotalEvalCount int64 `json:"totalEvalCount,omitempty"`
}

// Validate validates this datar summary flag
func (m *DatarSummaryFlag) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastEvaluatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DatarSummaryFlag) validateLastEvaluatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(m.LastEvaluatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("lastEvaluatedAt", "body", "date-time", m.LastEvaluatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this datar summary flag based on context it is used
func (m *DatarSummaryFlag) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DatarSummaryFlag) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DatarSummaryFlag) UnmarshalBinary(b []byte) error {
	var res DatarSummaryFlag
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
