// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DatarVariantEntry datar variant entry
//
// swagger:model datarVariantEntry
type DatarVariantEntry struct {

	// count
	Count int64 `json:"count,omitempty"`

	// variant ID
	VariantID int64 `json:"variantID,omitempty"`
}

// Validate validates this datar variant entry
func (m *DatarVariantEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this datar variant entry based on context it is used
func (m *DatarVariantEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DatarVariantEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DatarVariantEntry) UnmarshalBinary(b []byte) error {
	var res DatarVariantEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
