// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// Enricher enricher
//
// swagger:model enricher
type Enricher struct {

	// namespace-specific configuration; the jev namespace expects an object with a questions map
	Config any `json:"config,omitempty"`

	// whether the namespace is enabled by server configuration
	// Read Only: true
	Enabled *bool `json:"enabled,omitempty"`

	// enricher identity; a flag declares at most one per namespace
	// Required: true
	// Min Length: 1
	Namespace *string `json:"namespace"`

	// exact enriched property names this enricher contributes (e.g. @jev_plan_tier)
	// Read Only: true
	Properties []string `json:"properties"`

	// global enrichers are built into the server; flag enrichers are declared on the flag
	// Read Only: true
	// Enum: ["global","flag"]
	Scope string `json:"scope,omitempty"`
}

// Validate validates this enricher
func (m *Enricher) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNamespace(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScope(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Enricher) validateNamespace(formats strfmt.Registry) error {

	if err := validate.Required("namespace", "body", m.Namespace); err != nil {
		return err
	}

	if err := validate.MinLength("namespace", "body", *m.Namespace, 1); err != nil {
		return err
	}

	return nil
}

var enricherTypeScopePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["global","flag"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		enricherTypeScopePropEnum = append(enricherTypeScopePropEnum, v)
	}
}

const (

	// EnricherScopeGlobal captures enum value "global"
	EnricherScopeGlobal string = "global"

	// EnricherScopeFlag captures enum value "flag"
	EnricherScopeFlag string = "flag"
)

// prop value enum
func (m *Enricher) validateScopeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, enricherTypeScopePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Enricher) validateScope(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Scope) { // not required
		return nil
	}

	// value enum
	if err := m.validateScopeEnum("scope", "body", m.Scope); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this enricher based on the context it is used
func (m *Enricher) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEnabled(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProperties(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateScope(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Enricher) contextValidateEnabled(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "enabled", "body", m.Enabled); err != nil {
		return err
	}

	return nil
}

func (m *Enricher) contextValidateProperties(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "properties", "body", m.Properties); err != nil {
		return err
	}

	return nil
}

func (m *Enricher) contextValidateScope(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "scope", "body", m.Scope); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Enricher) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Enricher) UnmarshalBinary(b []byte) error {
	var res Enricher
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
