// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FlagSnapshotMaxID flag snapshot max ID
//
// swagger:model flagSnapshotMaxID
type FlagSnapshotMaxID struct {

	// max ID
	MaxID int64 `json:"maxID,omitempty"`
}

// Validate validates this flag snapshot max ID
func (m *FlagSnapshotMaxID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this flag snapshot max ID based on context it is used
func (m *FlagSnapshotMaxID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FlagSnapshotMaxID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FlagSnapshotMaxID) UnmarshalBinary(b []byte) error {
	var res FlagSnapshotMaxID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
