// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// JevQuestion jev question
//
// swagger:model jevQuestion
type JevQuestion struct {

	// confidence threshold
	// Maximum: 1
	// Minimum: 0
	ConfidenceThreshold *float64 `json:"confidenceThreshold,omitempty"`

	// choice expects an object of option to description; score expects an array of levels
	Criteria any `json:"criteria,omitempty"`

	// free-form model instructions as a string, object, or array
	// Required: true
	Instructions any `json:"instructions"`

	// type
	// Required: true
	// Enum: ["noul","choice","score"]
	Type *string `json:"type"`
}

// Validate validates this jev question
func (m *JevQuestion) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConfidenceThreshold(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstructions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JevQuestion) validateConfidenceThreshold(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ConfidenceThreshold) { // not required
		return nil
	}

	if err := validate.Minimum("confidenceThreshold", "body", *m.ConfidenceThreshold, 0, false); err != nil {
		return err
	}

	if err := validate.Maximum("confidenceThreshold", "body", *m.ConfidenceThreshold, 1, false); err != nil {
		return err
	}

	return nil
}

func (m *JevQuestion) validateInstructions(formats strfmt.Registry) error {

	if m.Instructions == nil {
		return errors.Required("instructions", "body", nil)
	}

	return nil
}

var jevQuestionTypeTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["noul","choice","score"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		jevQuestionTypeTypePropEnum = append(jevQuestionTypeTypePropEnum, v)
	}
}

const (

	// JevQuestionTypeNoul captures enum value "noul"
	JevQuestionTypeNoul string = "noul"

	// JevQuestionTypeChoice captures enum value "choice"
	JevQuestionTypeChoice string = "choice"

	// JevQuestionTypeScore captures enum value "score"
	JevQuestionTypeScore string = "score"
)

// prop value enum
func (m *JevQuestion) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, jevQuestionTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *JevQuestion) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this jev question based on context it is used
func (m *JevQuestion) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JevQuestion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JevQuestion) UnmarshalBinary(b []byte) error {
	var res JevQuestion
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
