// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PutDistributionsRequest put distributions request
//
// swagger:model putDistributionsRequest
type PutDistributionsRequest struct {

	// distributions
	// Required: true
	Distributions []*Distribution `json:"distributions"`
}

// Validate validates this put distributions request
func (m *PutDistributionsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDistributions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PutDistributionsRequest) validateDistributions(formats strfmt.Registry) error {

	if err := validate.Required("distributions", "body", m.Distributions); err != nil {
		return err
	}

	for i := 0; i < len(m.Distributions); i++ {
		if swag.IsZero(m.Distributions[i]) { // not required
			continue
		}

		if m.Distributions[i] != nil {
			if err := m.Distributions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("distributions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this put distributions request based on the context it is used
func (m *PutDistributionsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDistributions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PutDistributionsRequest) contextValidateDistributions(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Distributions); i++ {

		if m.Distributions[i] != nil {
			if err := m.Distributions[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("distributions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PutDistributionsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PutDistributionsRequest) UnmarshalBinary(b []byte) error {
	var res PutDistributionsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
