// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetFlagByNameHandlerFunc turns a function with the right signature into a get flag by name handler
type GetFlagByNameHandlerFunc func(GetFlagByNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFlagByNameHandlerFunc) Handle(params GetFlagByNameParams) middleware.Responder {
	return fn(params)
}

// GetFlagByNameHandler interface for that can handle valid get flag by name params
type GetFlagByNameHandler interface {
	Handle(GetFlagByNameParams) middleware.Responder
}

// NewGetFlagByName creates a new http.Handler for the get flag by name operation
func NewGetFlagByName(ctx *middleware.Context, handler GetFlagByNameHandler) *GetFlagByName {
	return &GetFlagByName{Context: ctx, Handler: handler}
}

/*GetFlagByName swagger:route GET /query query getFlagByName

GetFlagByName get flag by name API

*/
type GetFlagByName struct {
	Context *middleware.Context
	Handler GetFlagByNameHandler
}

func (o *GetFlagByName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetFlagByNameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
