// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFlagByNameParams creates a new GetFlagByNameParams object
// no default values defined in spec.
func NewGetFlagByNameParams() GetFlagByNameParams {

	return GetFlagByNameParams{}
}

// GetFlagByNameParams contains all the bound params for the get flag by name operation
// typically these are obtained from a http.Request
//
// swagger:parameters getFlagByName
type GetFlagByNameParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*name of the flag to query
	  Required: true
	  Min Length: 1
	  In: query
	*/
	FlagName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetFlagByNameParams() beforehand.
func (o *GetFlagByNameParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qFlagName, qhkFlagName, _ := qs.GetOK("flagName")
	if err := o.bindFlagName(qFlagName, qhkFlagName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetFlagByNameParams) bindFlagName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("flagName", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("flagName", "query", raw); err != nil {
		return err
	}

	o.FlagName = raw

	if err := o.validateFlagName(formats); err != nil {
		return err
	}

	return nil
}

func (o *GetFlagByNameParams) validateFlagName(formats strfmt.Registry) error {

	if err := validate.MinLength("flagName", "query", o.FlagName, 1); err != nil {
		return err
	}

	return nil
}
