// Code generated by go-swagger; DO NOT EDIT.

package constraint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateConstraintHandlerFunc turns a function with the right signature into a create constraint handler
type CreateConstraintHandlerFunc func(CreateConstraintParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateConstraintHandlerFunc) Handle(params CreateConstraintParams) middleware.Responder {
	return fn(params)
}

// CreateConstraintHandler interface for that can handle valid create constraint params
type CreateConstraintHandler interface {
	Handle(CreateConstraintParams) middleware.Responder
}

// NewCreateConstraint creates a new http.Handler for the create constraint operation
func NewCreateConstraint(ctx *middleware.Context, handler CreateConstraintHandler) *CreateConstraint {
	return &CreateConstraint{Context: ctx, Handler: handler}
}

/* CreateConstraint swagger:route POST /flags/{flagID}/segments/{segmentID}/constraints constraint createConstraint

CreateConstraint create constraint API

*/
type CreateConstraint struct {
	Context *middleware.Context
	Handler CreateConstraintHandler
}

func (o *CreateConstraint) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateConstraintParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
