// Code generated by go-swagger; DO NOT EDIT.

package constraint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteConstraintHandlerFunc turns a function with the right signature into a delete constraint handler
type DeleteConstraintHandlerFunc func(DeleteConstraintParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteConstraintHandlerFunc) Handle(params DeleteConstraintParams) middleware.Responder {
	return fn(params)
}

// DeleteConstraintHandler interface for that can handle valid delete constraint params
type DeleteConstraintHandler interface {
	Handle(DeleteConstraintParams) middleware.Responder
}

// NewDeleteConstraint creates a new http.Handler for the delete constraint operation
func NewDeleteConstraint(ctx *middleware.Context, handler DeleteConstraintHandler) *DeleteConstraint {
	return &DeleteConstraint{Context: ctx, Handler: handler}
}

/* DeleteConstraint swagger:route DELETE /flags/{flagID}/segments/{segmentID}/constraints/{constraintID} constraint deleteConstraint

DeleteConstraint delete constraint API

*/
type DeleteConstraint struct {
	Context *middleware.Context
	Handler DeleteConstraintHandler
}

func (o *DeleteConstraint) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteConstraintParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
