// Code generated by go-swagger; DO NOT EDIT.

package constraint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindConstraintsHandlerFunc turns a function with the right signature into a find constraints handler
type FindConstraintsHandlerFunc func(FindConstraintsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindConstraintsHandlerFunc) Handle(params FindConstraintsParams) middleware.Responder {
	return fn(params)
}

// FindConstraintsHandler interface for that can handle valid find constraints params
type FindConstraintsHandler interface {
	Handle(FindConstraintsParams) middleware.Responder
}

// NewFindConstraints creates a new http.Handler for the find constraints operation
func NewFindConstraints(ctx *middleware.Context, handler FindConstraintsHandler) *FindConstraints {
	return &FindConstraints{Context: ctx, Handler: handler}
}

/* FindConstraints swagger:route GET /flags/{flagID}/segments/{segmentID}/constraints constraint findConstraints

FindConstraints find constraints API

*/
type FindConstraints struct {
	Context *middleware.Context
	Handler FindConstraintsHandler
}

func (o *FindConstraints) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindConstraintsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
