// Code generated by go-swagger; DO NOT EDIT.

package datar

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/openflagr/flagr/swagger_gen/models"
)

// GetDatarSummaryOKCode is the HTTP code returned for type GetDatarSummaryOK
const GetDatarSummaryOKCode int = 200

/*
GetDatarSummaryOK summary of all flag traffic

swagger:response getDatarSummaryOK
*/
type GetDatarSummaryOK struct {

	/*
	  In: Body
	*/
	Payload *models.DatarSummaryResponse `json:"body,omitempty"`
}

// NewGetDatarSummaryOK creates GetDatarSummaryOK with default headers values
func NewGetDatarSummaryOK() *GetDatarSummaryOK {

	return &GetDatarSummaryOK{}
}

// WithPayload adds the payload to the get datar summary o k response
func (o *GetDatarSummaryOK) WithPayload(payload *models.DatarSummaryResponse) *GetDatarSummaryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get datar summary o k response
func (o *GetDatarSummaryOK) SetPayload(payload *models.DatarSummaryResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDatarSummaryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetDatarSummaryDefault generic error response

swagger:response getDatarSummaryDefault
*/
type GetDatarSummaryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetDatarSummaryDefault creates GetDatarSummaryDefault with default headers values
func NewGetDatarSummaryDefault(code int) *GetDatarSummaryDefault {
	if code <= 0 {
		code = 500
	}

	return &GetDatarSummaryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get datar summary default response
func (o *GetDatarSummaryDefault) WithStatusCode(code int) *GetDatarSummaryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get datar summary default response
func (o *GetDatarSummaryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get datar summary default response
func (o *GetDatarSummaryDefault) WithPayload(payload *models.Error) *GetDatarSummaryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get datar summary default response
func (o *GetDatarSummaryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDatarSummaryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
