// Code generated by go-swagger; DO NOT EDIT.

package datar

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDatarSummaryHandlerFunc turns a function with the right signature into a get datar summary handler
type GetDatarSummaryHandlerFunc func(GetDatarSummaryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDatarSummaryHandlerFunc) Handle(params GetDatarSummaryParams) middleware.Responder {
	return fn(params)
}

// GetDatarSummaryHandler interface for that can handle valid get datar summary params
type GetDatarSummaryHandler interface {
	Handle(GetDatarSummaryParams) middleware.Responder
}

// NewGetDatarSummary creates a new http.Handler for the get datar summary operation
func NewGetDatarSummary(ctx *middleware.Context, handler GetDatarSummaryHandler) *GetDatarSummary {
	return &GetDatarSummary{Context: ctx, Handler: handler}
}

/*
	GetDatarSummary swagger:route GET /datar/summary datar getDatarSummary

Aggregate traffic summary for all flags
*/
type GetDatarSummary struct {
	Context *middleware.Context
	Handler GetDatarSummaryHandler
}

func (o *GetDatarSummary) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewGetDatarSummaryParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
