// Code generated by go-swagger; DO NOT EDIT.

package datar

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/openflagr/flagr/swagger_gen/models"
)

// GetDatarFlagSummaryOKCode is the HTTP code returned for type GetDatarFlagSummaryOK
const GetDatarFlagSummaryOKCode int = 200

/*
GetDatarFlagSummaryOK flag analytics summary

swagger:response getDatarFlagSummaryOK
*/
type GetDatarFlagSummaryOK struct {

	/*
	  In: Body
	*/
	Payload *models.DatarFlagSummaryResponse `json:"body,omitempty"`
}

// NewGetDatarFlagSummaryOK creates GetDatarFlagSummaryOK with default headers values
func NewGetDatarFlagSummaryOK() *GetDatarFlagSummaryOK {

	return &GetDatarFlagSummaryOK{}
}

// WithPayload adds the payload to the get datar flag summary o k response
func (o *GetDatarFlagSummaryOK) WithPayload(payload *models.DatarFlagSummaryResponse) *GetDatarFlagSummaryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get datar flag summary o k response
func (o *GetDatarFlagSummaryOK) SetPayload(payload *models.DatarFlagSummaryResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDatarFlagSummaryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetDatarFlagSummaryDefault generic error response

swagger:response getDatarFlagSummaryDefault
*/
type GetDatarFlagSummaryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetDatarFlagSummaryDefault creates GetDatarFlagSummaryDefault with default headers values
func NewGetDatarFlagSummaryDefault(code int) *GetDatarFlagSummaryDefault {
	if code <= 0 {
		code = 500
	}

	return &GetDatarFlagSummaryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get datar flag summary default response
func (o *GetDatarFlagSummaryDefault) WithStatusCode(code int) *GetDatarFlagSummaryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get datar flag summary default response
func (o *GetDatarFlagSummaryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get datar flag summary default response
func (o *GetDatarFlagSummaryDefault) WithPayload(payload *models.Error) *GetDatarFlagSummaryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get datar flag summary default response
func (o *GetDatarFlagSummaryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDatarFlagSummaryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
