#!/bin/sh

if [ "$FLAGR_REMOTE_SQLITE_ENABLED" = "true" ] && [ "$FLAGR_DB_DBDRIVER" = "sqlite3" ]; then
    curl -u $FLAGR_REMOTE_SQLITE_USERNAME:$FLAGR_REMOTE_SQLITE_PASSWORD $FLAGR_REMOTE_SQLITE_URL -o $FLAGR_DB_DBCONNECTIONSTR;
fi
