// Code generated by go-swagger; DO NOT EDIT.

package enricher

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateEnricherHandlerFunc turns a function with the right signature into a create enricher handler
type CreateEnricherHandlerFunc func(CreateEnricherParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateEnricherHandlerFunc) Handle(params CreateEnricherParams) middleware.Responder {
	return fn(params)
}

// CreateEnricherHandler interface for that can handle valid create enricher params
type CreateEnricherHandler interface {
	Handle(CreateEnricherParams) middleware.Responder
}

// NewCreateEnricher creates a new http.Handler for the create enricher operation
func NewCreateEnricher(ctx *middleware.Context, handler CreateEnricherHandler) *CreateEnricher {
	return &CreateEnricher{Context: ctx, Handler: handler}
}

/*
	CreateEnricher swagger:route POST /flags/{flagID}/enrichers enricher createEnricher

CreateEnricher create enricher API
*/
type CreateEnricher struct {
	Context *middleware.Context
	Handler CreateEnricherHandler
}

func (o *CreateEnricher) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewCreateEnricherParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
