// Code generated by go-swagger; DO NOT EDIT.

package enricher

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/openflagr/flagr/swagger_gen/models"
)

// PutEnricherOKCode is the HTTP code returned for type PutEnricherOK
const PutEnricherOKCode int = 200

/*
PutEnricherOK enricher just updated

swagger:response putEnricherOK
*/
type PutEnricherOK struct {

	/*
	  In: Body
	*/
	Payload *models.Enricher `json:"body,omitempty"`
}

// NewPutEnricherOK creates PutEnricherOK with default headers values
func NewPutEnricherOK() *PutEnricherOK {

	return &PutEnricherOK{}
}

// WithPayload adds the payload to the put enricher o k response
func (o *PutEnricherOK) WithPayload(payload *models.Enricher) *PutEnricherOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put enricher o k response
func (o *PutEnricherOK) SetPayload(payload *models.Enricher) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutEnricherOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PutEnricherDefault generic error response

swagger:response putEnricherDefault
*/
type PutEnricherDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutEnricherDefault creates PutEnricherDefault with default headers values
func NewPutEnricherDefault(code int) *PutEnricherDefault {
	if code <= 0 {
		code = 500
	}

	return &PutEnricherDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put enricher default response
func (o *PutEnricherDefault) WithStatusCode(code int) *PutEnricherDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put enricher default response
func (o *PutEnricherDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put enricher default response
func (o *PutEnricherDefault) WithPayload(payload *models.Error) *PutEnricherDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put enricher default response
func (o *PutEnricherDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutEnricherDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
