// Code generated by go-swagger; DO NOT EDIT.

package enricher

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutEnricherHandlerFunc turns a function with the right signature into a put enricher handler
type PutEnricherHandlerFunc func(PutEnricherParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutEnricherHandlerFunc) Handle(params PutEnricherParams) middleware.Responder {
	return fn(params)
}

// PutEnricherHandler interface for that can handle valid put enricher params
type PutEnricherHandler interface {
	Handle(PutEnricherParams) middleware.Responder
}

// NewPutEnricher creates a new http.Handler for the put enricher operation
func NewPutEnricher(ctx *middleware.Context, handler PutEnricherHandler) *PutEnricher {
	return &PutEnricher{Context: ctx, Handler: handler}
}

/*
	PutEnricher swagger:route PUT /flags/{flagID}/enrichers/{namespace} enricher putEnricher

PutEnricher put enricher API
*/
type PutEnricher struct {
	Context *middleware.Context
	Handler PutEnricherHandler
}

func (o *PutEnricher) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewPutEnricherParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
