// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Flagr
Flagr is a feature flagging, A/B testing and dynamic configuration microservice


    Schemes:
      http
    Host: localhost
    BasePath: /api
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
