// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Flagr
Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is "/api/v1".



    Schemes:
      http
    Host: localhost
    BasePath: /api/v1
    Version: 1.0.15

    Consumes:
    - application/json

    Produces:
    - application/json
    - application/octet-stream

swagger:meta
*/
package restapi
