name: cd_changelog

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  create_changelog_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create changelog PR
        uses: technote-space/create-pr-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          EXECUTE_COMMANDS: |
            npm install -g auto-changelog
            auto-changelog
          COMMIT_MESSAGE: 'chore: update changelog'
          PR_BRANCH_PREFIX: 'changelog/'
          PR_BRANCH_NAME: 'chore-update-changelog-${PR_ID}'
          PR_TITLE: 'chore: update changelog'
          PR_BODY: |
            <!-- START pr-commits -->
            <!-- END pr-commits -->
            ## Base PullRequest
            ${PR_TITLE} (${PR_NUMBER_REF})
            ## Command results
            <details>
              <summary>Details: </summary>
              ${COMMANDS_OUTPUT}
            </details>
            ## Changed files
            <details>
              <summary>${FILES_SUMMARY}: </summary>
              ${FILES}
            </details>
