# ******** NOTE ********
# Deploy the https://try-openflagr.herokuapp.com demo service on main branch merges
#
name: cd_heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    environment: heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "try-openflagr"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
