name: Deploy App

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    env:
      # ProxySQL Database Configuration
      FLAGR_DB_DBDRIVER: ${{ secrets.FLAGR_DB_DBDRIVER }}
      FLAGR_DB_DBCONNECTIONSTR: ${{ secrets.FLAGR_DB_DBCONNECTIONSTR }}
      PROXYSQL_MYSQL_USER: ${{ secrets.PROXYSQL_MYSQL_USER }}
      PROXYSQL_MYSQL_PASSWORD: ${{ secrets.PROXYSQL_MYSQL_PASSWORD }}
      PROXYSQL_MYSQL_SCHEMANAME: ${{ secrets.PROXYSQL_MYSQL_SCHEMANAME }}


      # Monitoring
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}


    steps:
      - name: Debug database URL
        run: echo "DATABASE_URL=${{ env.FLAGR_DB_DBCONNECTIONSTR }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out code
        uses: actions/checkout@v3
      # - name: Cache
      #  uses: actions/cache@v4
      #  with:
      #   path: |
      #      ~/.cargo
      #      target
      #    key: rust-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      #    restore-keys: |
      #      rust-${{ runner.os }}-
      #      rust-
      #    save-always: true
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_GITHUB_ACTIONS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_GITHUB_ACTIONS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push App image to Amazon ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.go
          push: true
          tags: |
            ${{ secrets.AWS_ECR_REPOSITORY }}:flagr-app
          cache-from: type=registry,ref=${{ secrets.AWS_ECR_REPOSITORY }}:rust-build-cache
          cache-to: type=registry,ref=${{ secrets.AWS_ECR_REPOSITORY }}:rust-build-cache,mode=max,image-manifest=true,oci-mediatypes=true

      - name: Fetch existing task definition
        id: fetch-task-def
        run: |
          aws ecs describe-task-definition --task-definition paubox-iam-${{ inputs.environment }}-webapp-task > ecs-task-definition.json

      - name: Clean up downloaded task definition
        run: |
          jq '.taskDefinition' ecs-task-definition.json > no-task-definition.json
          cat no-task-definition.json | jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy) | .containerDefinitions[0].environment = []' > ecs-task-definition-trimmed.json

      - name: Render Amazon ECS task definition
        id: render-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-definition-trimmed.json
          container-name: iam-app
          image: ${{ secrets.AWS_ECR_REPOSITORY }}:rust-latest
          environment-variables: |
            FLAGR_DB_DBDRIVER=${{ secrets.FLAGR_DB_DBDRIVER }}
            FLAGR_DB_DBCONNECTIONSTR=${{ secrets.FLAGR_DB_DBCONNECTIONSTR }}
            PROXYSQL_MYSQL_USER=${{ secrets.PROXYSQL_MYSQL_USER }}
            PROXYSQL_MYSQL_PASSWORD=${{ secrets.PROXYSQL_MYSQL_PASSWORD }}
            PROXYSQL_MYSQL_SCHEMANAME=${{ secrets.PROXYSQL_MYSQL_SCHEMANAME }}
            ENVIRONMENT=${{ vars.ENVIRONMENT }}


      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-container.outputs.task-definition }}
          service: webapp-service
          cluster: paubox-iam-${{ inputs.environment }}
          # wait-for-service-stability: true
