name: Deploy to Production

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-proxysql:
    uses: ./.github/workflows/deploy-proxysql.yml
    with:
      environment: production
    secrets: inherit