// Wiki: https://acikota.atlassian.net/wiki/spaces/Platform/pages/311787592/Centralising+stages+of+the+pipeline+for+golang+backend+services
@Library('Allen_Shared_Libraries') _
commonPipelineForStageToProdPromotion(
    environment: [
        Service_Name : "flagr",
        Target_Environment : "production",
        DEPLOY_GITOPS_REPO : "central-gitops-repo",
        SOURCE_FILE : "app-charts-live/flagr/values-stage.yaml",
        TARGET_FILE : "app-charts-live/flagr/values-prod.yaml",
        DEPLOY_TARGET_BRANCH : "main",
        Slack_Channel : "#central-function-events",
        ProdSlack_Channel : "#prod-release"
    ]
)
